version: '3.8'
services:
  web:
    build: .
    container_name: perkara_app_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
  db:
    image: mysql:5.7
    container_name: perkara_app_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: perkara_db
      MYSQL_USER: perkara_user
      MYSQL_PASSWORD: perkara_pass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
